In [1]:
import numpy as np
from cython_example_proj import c_square, c_rms, c_rmse
import time

# Test

## Test Square Function

In [2]:
print(c_square(10))

100

## Test Root Mean Square

In [3]:
a= np.array([1,2,3,4,5]).astype('int32')
print('a:',a)
print(c_rms(a,5))

('a:', array([1, 2, 3, 4, 5], dtype=int32))
3.31662487984

## Test Root Mean Square Error

In [39]:
# Basic test with case 1
b1=a
b2=a*2
print('b1:',b1)
print('b2:',b2)
print(c_rmse(b1,b2,5))

('b1:', array([1, 2, 3, 4, 5], dtype=int32))
('b2:', array([ 2,  4,  6,  8, 10], dtype=int32))
3.31662487984

In [40]:
# Basic test with case 2
arr_size=500
b1=np.random.randint(100,size=arr_size).astype('int32')
b2=b1+np.random.randint(low=-10,high=10,size=arr_size).astype('int32')
print('b1:',b1)
print('b2:',b2)
print(c_rmse(b1,b2,arr_size))

('b1:', array([54, 78,  0, 43, 69, 18, 23, 60, 83, 41, 45, 26, 94, 30, 94, 47, 59,
       53, 87,  3, 99, 69, 45, 17, 41, 85, 44, 55, 59, 60, 94, 64, 55, 14,
       51, 97, 52, 27,  9,  3, 58,  9, 91,  2, 61, 44, 44, 67, 72, 80, 24,
       91, 71, 29, 74, 49, 35, 55,  0, 33, 71, 35, 47, 64, 40, 67, 60, 11,
       14, 95, 93, 45, 54, 36, 21, 63, 76, 93, 23,  9, 58, 17, 25, 82,  6,
        1, 65,  1, 50,  2, 14, 51, 44, 64,  7, 21, 14, 54, 69, 56, 93, 98,
       46, 96, 85, 58, 96, 84,  0, 85, 37, 70,  8, 51, 33, 22, 33, 12, 92,
       84, 13, 15, 27, 58,  0, 57, 24, 14, 15, 55, 34, 89, 98, 72, 76, 32,
        5, 77, 95, 16, 23, 35, 89, 92, 99, 38, 81, 67, 15, 66, 59, 18, 61,
       58, 44, 76, 13, 61, 67, 97, 85, 98, 52, 23, 27,  0, 26, 45, 34,  6,
       81, 49, 61, 79, 84, 15, 91, 28, 32, 79, 37,  7, 86, 54, 58, 89, 74,
       42, 29, 66, 47, 50, 22, 44, 47, 17, 73, 40, 22, 63, 61, 19, 54, 48,
       33, 82, 10, 16, 77, 34, 93, 92, 38,  9, 69, 61, 40, 56, 75, 84, 95,
       45, 91,  5, 17, 23, 95, 33, 69, 37, 15,  1, 94, 59, 13, 57, 76, 29,
       23,  4, 38, 39, 93, 96, 53, 77, 88, 70, 46, 60, 80, 36, 70,  2, 93,
       34, 98, 61, 71, 73,  7, 90, 72, 58, 48, 39, 44, 24, 72,  2, 18, 97,
        2, 17, 72, 42, 79, 27, 40, 54, 16,  0, 39, 44, 33, 24,  4, 29, 77,
        9, 79, 86,  7, 91, 56, 64, 17, 32, 11, 16, 34, 73,  1, 78, 29, 94,
       14,  8, 66, 19, 29, 88, 18, 69, 82, 49, 67, 63, 17, 89, 21,  8,  3,
       51, 62, 64, 79, 97, 65, 24, 70, 73, 12, 88, 52, 47, 87, 82, 62, 24,
       18, 57, 50,  5, 46, 34,  7, 71, 55, 42, 73, 65,  1, 41, 22, 93, 90,
       77, 76, 42, 94, 34, 96, 38, 49, 94, 58, 51, 47, 85, 92,  7, 76, 88,
       66,  9, 98, 78, 76, 65,  5, 63, 66, 41, 19, 32, 57, 55, 70,  8, 95,
       75, 86, 25, 81, 56, 53, 39, 70, 22, 87, 98, 24, 71, 92,  8, 47, 97,
        5, 66, 44, 98, 93, 71, 54, 76,  6,  4, 36, 26, 59, 37,  7, 38, 94,
       11, 72, 94, 25, 95, 38, 62, 60, 25, 81, 82, 62, 66, 89, 23, 91, 59,
       88, 59, 70, 31,  0, 32, 97, 39, 10, 77, 10, 53, 91, 98,  2, 74, 41,
        9, 84, 70, 57, 52, 86, 68, 36, 35, 91, 43, 54, 19, 14, 72, 76,  8,
       92, 82, 75, 27, 87, 99, 87,  6, 48, 95, 69, 82, 15, 52, 37, 97, 49,
       16, 90,  4,  3, 82, 39, 58], dtype=int32))
('b2:', array([ 50,  71,   6,  33,  78,  26,  17,  54,  81,  45,  48,  17,  98,
        22,  87,  46,  57,  62,  88,   1,  95,  74,  52,  20,  42,  94,
        47,  51,  55,  50,  95,  59,  50,  10,  52,  99,  47,  27,  15,
        -3,  59,   3,  85,   7,  59,  43,  35,  57,  68,  70,  28,  95,
        65,  34,  66,  55,  43,  59,  -1,  42,  71,  29,  47,  61,  49,
        76,  67,  17,  22,  99,  92,  47,  54,  35,  30,  70,  74,  93,
        16,   6,  55,  15,  17,  85,  -2,  -6,  68,   5,  57,  -3,  15,
        60,  50,  66,  14,  28,  14,  59,  71,  50,  96, 107,  42,  93,
        83,  54,  98,  86,   6,  79,  34,  71,  12,  47,  31,  20,  35,
        16,  89,  79,  22,  21,  31,  64,   4,  60,  15,  11,  16,  60,
        43,  89, 107,  79,  66,  22,   0,  85, 102,  25,  32,  37,  80,
        99, 104,  37,  75,  70,  22,  60,  51,  16,  64,  51,  46,  83,
        13,  65,  59, 102,  90,  94,  46,  14,  31,  -1,  24,  47,  35,
        12,  76,  53,  59,  87,  77,   9,  82,  36,  36,  88,  31,  -3,
        94,  49,  55,  79,  70,  49,  22,  69,  51,  51,  18,  40,  43,
        15,  80,  40,  12,  69,  61,  25,  56,  43,  41,  79,   7,  16,
        85,  28,  97,  84,  35,  11,  67,  66,  35,  51,  77,  87,  94,
        50,  85,   6,  16,  29,  93,  23,  66,  29,  18,  -5, 102,  58,
         8,  52,  79,  30,  32,  13,  40,  48,  84,  98,  47,  73,  91,
        64,  54,  60,  72,  37,  70,  -7,  86,  25,  97,  55,  72,  72,
         1,  80,  75,  59,  53,  39,  41,  17,  71,  -1,  12,  99,  -3,
         9,  81,  45,  72,  19,  41,  63,  25,   1,  40,  37,  33,  26,
         4,  38,  80,   4,  78,  77,  -3,  87,  54,  60,  13,  38,  20,
        18,  41,  65,  -1,  84,  24,  90,  15,  10,  62,  17,  30,  79,
        12,  67,  87,  42,  71,  66,  25,  98,  30,   0,  11,  45,  52,
        67,  81, 106,  68,  28,  76,  78,  20,  97,  46,  52,  93,  85,
        62,  24,  23,  50,  55,  -2,  51,  32,  -3,  71,  46,  36,  64,
        58,  -4,  31,  24, 102,  99,  69,  83,  42,  84,  42, 100,  36,
        53, 100,  54,  56,  44,  80,  84,   2,  70,  87,  62,  14,  96,
        87,  72,  60,  12,  60,  57,  34,  16,  34,  55,  45,  70,   0,
        95,  75,  90,  31,  88,  56,  57,  41,  61,  28,  77,  98,  30,
        63,  97,  13,  45,  87,   8,  66,  41,  91,  84,  73,  50,  85,
        15,   5,  45,  23,  53,  32,   5,  28, 100,  19,  70,  97,  27,
        94,  47,  65,  66,  26,  79,  87,  67,  58,  96,  17,  98,  55,
        97,  66,  69,  22,  -9,  26,  93,  36,   0,  72,  15,  61,  84,
        92,   6,  66,  31,   1,  93,  65,  65,  61,  83,  61,  31,  43,
        89,  52,  55,  25,  14,  77,  80,  14,  94,  86,  81,  28,  80,
        97,  95,  -1,  55,  87,  73,  86,   7,  49,  35, 102,  39,  20,
        99,  -1,   8,  83,  33,  60], dtype=int32))
5.75829839706

In [41]:
# numpy version rmse function
def rmse(arr1, arr2, n):
    square=0
    for i in range(n):
        square+=(arr1[i]-arr2[i])**2
    return np.sqrt(square/np.float(n)).astype(np.float32)

In [42]:
# Compare time between two different implementation
t = time.time()
cc_rmse=c_rmse(b1,b2,arr_size)
print('cython rmse: %07f'%cc_rmse)
print("cython finished : %f s"%(time.time() - t))

t = time.time()
np_rmse=rmse(b1,b2,arr_size)
print('cython rmse: %07f'%np_rmse)
print("numpy finished : %f s"%(time.time() - t))

print(cc_rmse-np_rmse)

cython rmse: 5.758298
cython finished : 0.000405 s
cython rmse: 5.758298
numpy finished : 0.005574 s
0.0